# Site
name: 'Lightview'
description: 'Welcome to Lightview.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
email: 'arianna@lightview.it'
#url: 
google_analytics: 'UA-38797527-3'
disqus: 'lightview'
#mailchimp-list: ''
include: ["_pages"]
permalink: /blog/:categories/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Sal
      site:           https://lightview.it
      avatar:         /assets/images/avatar3.jpg
      bio:            "Hi, I am Sal, the author of this website. I hope you like it! "
      email:          arianna@lightview.it
      twitter:        
      linkedin:       https://www.linkedin.com/in/arianna-carta-855b9a4/
      donate:         https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3X9DQD5RDUTUN&source=url

    arianna:
      name:           Arianna Carta
      site:           https://lightview.it
      avatar:         /assets/images/avatar1.jpeg
      bio:            "Ciao, I am Arianna, the author of this website. Please follow me on Linkedin for updates and let me know if something can be improved in my articles."
      email:          arianna@lightview.it
      twitter:        
      linkedin:       https://www.linkedin.com/in/arianna-carta-855b9a4/
      donate:         https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3X9DQD5RDUTUN&source=url

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: arianna
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Paginate
paginate: 10
paginate_trail: 2
paginate_show_first_and_last: true
paginate_path: /page:num/



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]